### ISSUE TITLE
DateTime lost precision in Release version of App

### ISSUE THREAD

**Issue by apachucy** [simolus3/drift#1387]
pubspec:
moor: ^4.4.1
moor_generator: ^4.4.1

Table:
class EventDates extends Table {
  IntColumn get id => integer().autoIncrement()();

  IntColumn get eventId => integer()();

  DateTimeColumn get eventDate => dateTime()();

  static EventDate fromDate(int eventId, DateTime date) => EventDate(
        id: eventId,
        eventId: eventId,
        eventDate: date,
      );
}

This table return two different format of date that depends on buildVariant in Android.
In case of debug app receive full date format dd/MM/yyyy HH:mm
In case of release app there is dd/MM/yyyy - library loose precision (there is no hours - HH:mm)
From docs:
 Note that [DateTime] values are stored on a second-accuracy.
I get it, but it should work the same in debug/release mode. Is there a way to have full accuracy in release mode?

Sample:
 I/flutter: current date when saving:2021-10-07 11:00:00.000
 I/flutter: current date when saving:2021-10-07 10:00:00.000

 I/flutter: current date when loading:2021-10-07 00:00:00.000
 I/flutter: current date when loading:2021-10-07 00:00:00.000

**Comment by simolus3** [comment]
This looks really strange, it shouldn't depend on whether you're in debug/release mode at all and I haven't seen this problem before.

Due to unfortunate legacy reasons, moor stores and recovers datetime in the local time zone (as opposed to utc) #286. I wonder if this may have something to do with this, but it probably shouldn't.
One solution is to use a custom [`TypeConverter`](https://moor.simonbinder.eu/docs/advanced-features/type_converters/) that's responsible for storing dates in the format you want.

**Comment by simolus3** [comment]
I think I need more information to see what's going on here. Are you just querying the datetime column or are you using complex date time expressions provided by drift? I'll re-open the issue if you have more information or perhaps a way to reproduce this, but since I have never encountered and since there will now be another way of storing datetimes, I can't really act on this issue as it is.
