### ISSUE TITLE
Aggregate function that creates a dart list

### ISSUE THREAD

**Issue by LeFrosch** [simolus3/drift#1634]
**Is your feature request related to a problem? Please describe.**
I’m currently working on a project where I have to organise profiles with multiple profile pictures, thus I have created the following tables:
```sql
CREATE TABLE profile (
    uuid TEXT NOT NULL PRIMARY KEY,
    ...
);

CREATE TABLE image (
    uuid TEXT NOT NULL,
    id TEXT NOT NULL,
    ...

    FOREIGN KEY (uuid) REFERENCES profile (uuid) ON DELETE CASCADE,
    PRIMARY KEY (id)
);
```
Now I want to retrieve one profile with a specific uuid and all it’s images. At first the query seams straight forward:
```sql
getProfile(REQUIRED :uuid AS TEXT): 
SELECT p.**, i.**
FROM profile as p
JOIN image as i USING (uuid)
WHERE p.uuid = :uuid;
```
But this query would return an array of [(the profile, image1),  (the profile, image2), …], with the following generated result type:
```dart
class GetProfileResult {
  final ProfileData p;
  final ImageData i;
  GetProfileResult({
    required this.p,
    required this.i,
  });
}
```

**Describe the solution you'd like**
The perfect return for this query would be (the profile, [image1, image2, …]). Therefore, my feature request would be an aggregate function that creates a dart list. Like: 
```sql
getProfile(REQUIRED :uuid AS TEXT): 
SELECT p.**, TO_LIST(i.**)
FROM profile as p
JOIN image as i USING (uuid)
WHERE p.uuid = :uuid
GROUP BY p.uuid;
```
And a result type like:
```dart
class GetProfileResult {
  final ProfileData p;
  final List<ImageData> i;
  GetProfileResult({
    required this.p,
    required this.i,
  });
}
```
In my opinion this is quite a common use case and an aggregate function like this could be very useful. I would create a PR that tries to implement this feature, but I don’t know where to start and if this would be possible?

**Comment by simolus3** [comment]
While this certainly is a cool feature, it will require a lot of work to get right :) Internally, we'd have to split the queries into two steps:

1. First, load the relevant profiles and store them in an intermediate Dart list
2. Then, go through each profile and load matching images in a separate query.

Rewriting the queries will be quite hard for general SQL queries. It might be a bit easier if we add a syntax where the nested SQL needs to be written down explicitly, maybe:

```sql
getProfile(REQUIRED :uuid AS TEXT): 
SELECT p.**, LIST(SELECT * FROM images WHERE uuid = p.uuid)
FROM profile as p
WHERE p.uuid = :uuid
GROUP BY p.uuid;
```

Still, this requires plenty of work in the generator. I can point you to some relevant sources if you want to start working on it.

**Comment by LeFrosch** [comment]
Your approach looks easier and should be sufficient. But the group by in your example could be dropped when using this approach?

It would be great if you could point out some sources which could be relevant when implementing this :)

**Comment by LeFrosch** [comment]
I thought a little bit more about your approach and came up with an idea how this could be realised. The goal would be to generate subqueries when mapping the results of the row. For example:
```sql
getProfile(REQUIRED :uuid AS TEXT):
SELECT 
    p.** AS profile,
    LIST(SELECT * FROM image AS i WHERE i.uuid = p.uuid /* or :uuid */) AS images
FROM profile AS p
WHERE p.uuid = :uuid;
```
Should generated the following code:
```dart
Selectable<GetProfileResult> getProfile(String uuid) {
  return customSelect(
      'SELECT \n    "p"."uuid" AS "nested_0.uuid", "p"."name" AS "nested_0.name"\nFROM profile AS p\nWHERE p.uuid = :uuid',
      variables: [
        Variable<String>(uuid)
      ],
      readsFrom: {
        profile,
      }).map((QueryRow row) async {
    return GetProfileResult(
      profile: profile.mapFromRow(row, tablePrefix: 'nested_0'),
      images: await customSelect(
          'SELECT * FROM image AS i WHERE i.uuid = :p_uuid',
          variables: [
            Variable<String>(row.read('uuid'))
          ],
          readsFrom: {
            image,
          }).map<ImageData>(image.mapFromRow).get(),
    );
  });
}
```
The async support for the map is fairly easy due to the async nature of the Selectable, but I’m not quite sure what would be the best way to read data from the row and how to inject it into the subquery. And I added[^1] AS support for the nested star columns in my fork to familiarise myself with your codebase. 
[^1]: rather got it working, idk if it’s any good

**Comment by simolus3** [comment]
> But the group by in your example could be dropped when using this approach?

Oh right, exactly!

> It would be great if you could point out some sources which could be relevant when implementing this :)

Sure! So I would probably implement this by subclassing `ResultColumn` in the `sqlparser` package. At the moment, we have three kinds of columns:

- `StarResultColumn`, which represents things like `*` or `table.*` in a column list
- `ExpressionResultColumn`, which represents expressions being used in a select clause
- `NestedStarResultColumn`, which is drift-specific and represents the `**` syntax.

Inside `sqlparser/lib/src/ast/moor/`, you can add a say `NestedQueryColumn` that wraps a `SelectStatement` in a similar fashion. Next up would be parsing, which is implemented in `sqlparser/lib/src/reader`. You'll probably want to add a `nested` token in `reader/tokenizer/token.dart` and add it as a drift-specific keyword. In this parser, [this method](https://github.com/simolus3/moor/blob/41472d64ecb32a1597ce2bd295054f41c724d5ee/sqlparser/lib/src/reader/parser.dart#L1900-L1939) needs changing to also consider `NESTED` result columns. You can take a look at some parser testcases in `sqlparser/test/parser` when writing your own tests (which is also helpful for debugging the parser in general).

How to implement this in the generator is not as obvious, but relevant sources could be `drift_dev/lib/src/writer/queries/query_writer.dart` which is generating query code and files in `drift_dev/lib/src/analyzer/sql_queries` which does intermediate analysis. You can take a look at the `explicit_alias_transformer` as an example for rewriting queries. Btw, the writer currently has two modes: One in which the source string is patched to support things like array variables in generated code, and one where the generated SQL is created from the AST alone. The later is not enabled by default yet, but MUCH easier to work with since you can transform SQL queries which I imagine is useful here. I think it's fine if we require the new generation mode for this feature.

**Comment by simolus3** [comment]
> but I’m not quite sure what would be the best way to read data from the row and how to inject it into the subquery

I think we can add all the expressions that come from the outer query but are used in the inner query as a result column to the outer query. So if e.g. we had

```sql
SELECT 
    p.** AS profile,
    LIST(SELECT * FROM image AS i WHERE i.uuid = p.uuid /* or :uuid */) AS images
```

Then `p.uuid` would be that expression. So, we can transform the outer query to

```sql
SELECT p.** AS profile, p.uuid AS captured_var_1
  -- subject to further pre-processing...
```

This `capture_var_1` would not be added into the  generated result set and hidden from the user, but since it's there we can then use `read('captured_var_1')` in the generated code.

**Comment by LeFrosch** [comment]
First of all, thank you for the help :) Your collection of relevant source files was very helpful. The parsing was easy to implement, but I’m not sure how to proceed with the generation. The problem is[^1], you did not design the `QueryWriter` and the `QueryHandler` with recursion[^2] in mind. There are tree solutions:
- Rewrite the `QueryWriter` and `QueryHandler` using side effect free functions and pass all the required data around.
- Creating a new `QueryWriter` or `QueryHandler` object for the nested queries. But I’m not sure how I would turn a `SelectStatement` into `DeclaredQuery`[^3].
- Extract all nested queries and create private top level queries[^4], because these could probably be described with a `DeclaredQuery` thing.

[^1]: with my understanding
[^2]: for example calling again `_inferResultSet` for the nested select request
[^3]: this was probably never intended
[^4]: like normal queries but the name starts with `_`

**Comment by simolus3** [comment]
I'm somewhat in favor of option 1. I think we mostly just have to avoid using `context.root` when inferring result sets and instead pass down the AST node for which the result set should be inferred.

- IMO a `DeclaredQuery` should be, well, a declared query. So a query with nested subqueries is still a single `DeclaredQuery`. So this works best with option 1.
- We can either expand the `SqlSelectQuery` class or add a new `SqlQuery`-subclass for analyzed queries using nested subqueries. We should probably store the transformed AST for all the steps somewhere in that class.
