### ISSUE TITLE
Append `groupBy` clause to `as`method of extended `View` results in parse error

### ISSUE THREAD

**Issue by myacera100** [simolus3/drift#1740]
I defined some views by extending from `View` class and followed the example given by documentation. The build process ran well for the preceding ones, but failed after I append one `groupBy` clause to the backing select-statement in `as()` method of this `TestingRemoteMeterFeed` view. Is this an expected behavior as I did not see extra clause after `join()` in documentation?

The following snap shows parse error: `Failed to parse view as() query`

<img width="731" alt="屏幕截图 2022-03-09 093706" src="https://user-images.githubusercontent.com/81943962/157356191-47349d2f-c36a-4557-800a-073294341e22.png">

**Comment by simolus3** [comment]
We don't currently support these advanced queries in the Dart API for views, see also https://github.com/simolus3/drift/discussions/1696.

The reason is that we need to figure out which columns are part of a view (and that includes table columns referenced in `select`). This doesn't really work for arbitrarily complex Dart queries. In a future (breaking) release, we could ignore change Dart views to an API that doesn't require parsing the `Query as => ...` getter.

----

@westito Do you think something that doesn't require parsing the Dart query code could work? We could have users define all expressions to include explicitly (so something like `Expression<int> get foo => users.foo` instead of `select([..., users.foo])` implicitly adding a column). Then we'd just have to check that the select contains all columns defined in the view, which should also be possible at runtime. It's slightly less convenient for common cases when selecting columns from tables, but allows users to define complex views.

**Comment by westito** [comment]
This is just a bug in code parser. Not handles this `..` cascade operator. I'll fix it tomorrow.
