### ISSUE TITLE
Join on custom query defined in a sql.drift file

### ISSUE THREAD

**Issue by johnmcconnell** [simolus3/drift#1752]
**Describe the solution you'd like**
Suppose I have a custom defined query in a `custom_query.sql.drift` file:

```sql
customQuery:
SELECT * FROM relationships;
```

I would like to be able to join with this query using the dart query interface. For example,

```dart
db.customQuery
    .join([
       innerJoin(db.items, db.items.uuid.equals(db.customQuery.itemUuid),
     ])
```

What's the best way to achieve this? Or is this not currently supported? I'm be interested in getting this supported.

**Comment by simolus3** [comment]
No, this is not currently supported. It's possible to exchange parts of queries in drift files with [dart components](https://drift.simonbinder.eu/docs/using-sql/drift_files/#dart-interop), so that you can add things like expressions or ordering clauses as Dart parameters. However, embedding a whole drift-defined query into a Dart query is not possible. I don't think we'll ever be able to support that for all queries, since some drift features like [list subqueries](https://drift.simonbinder.eu/docs/using-sql/drift_files/#list-subqueries) require a transformation across multiple SQL statements.

Perhaps if you have a compelling example that would be much easier to write with this feature, I can take a look at what it takes to support that :D But at the moment, I think views should cover most of this feature.

**Comment by simolus3** [comment]
Great! FWIW you can also define a view in a drift file and reference in Dart queries if you prefer SQL.
