### ISSUE TITLE
Is there any way to check if DataClass has foreign key relations?

### ISSUE THREAD

**Issue by mateoKutnjak** [simolus3/drift#1768]
I need that because in order to sync some DataClass objects from database with remote server, its dependencies must be synced first. Example: In order to sync Car DataClass which has foreign key relation with User DataClass (owner foreign key), I have to sync User object first because maybe User it does not exist on remote server yet and sending Car object to remote server without existance of User object would throw non-existent foreign key object exception.

I would need to check if DataClass has foreign key relations and to which DataClass it is related to. Is that possible?

**Comment by simolus3** [comment]
This information isn't really exposed at the moment, and I don't think drift _should_ be exporting that information. It would increase the API surface a lot (if we expose column constraints as structured classes), increases code size and isn't relevant for most users.

You can, at runtime, iterate over all columns from a given table and check if they have a foreign key constraint to order your synchronization logic. But I think it will be a lot easier if you just implement that manually. If you know car has a foreign key relation to user (you should because you're writing the tables :D), then you can also respect this ordering when it comes to synchronization.
