### ISSUE TITLE
Providing "initialData" param on FutureBuilder/StreamBuilder

### ISSUE THREAD

**Issue by adummy832** [simolus3/drift#1772]
Hello! Before anything else very much thanks for this 
wonderful package and your unwavering support on it! :)

Based on this [article](https://ishouldgotosleep.com/posts/hero-widget-working-only-when-going-back-in-flutter/), FutureBuilder/StreamBuilder needs an "initialData" parameter in order for
Hero widget to work but I cannot provide it because data fetch only happens at runtime.

Is there some kind of built-in helper function on moor/drift to solve this issue?
Like calling a function e.g **"Categories.initialData"** or extending some class e.g **"Streamable"** 
or anything for streams/futures?

I'm really stuck on this, any insights of your will be appreciated. Thanks again!
Also provided simple snippet to recreate this issue.

### Query
```dart
Future<Category> getCategory(int id) async {
  return await (select(categories)..where((category) => category.id.equals(id)))
      .getSingle();
}
```

### Page 1
```dart
class TestIndex extends StatelessWidget {
  const TestIndex({ Key? key }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final _navigator = Navigator.of(context);

    return Scaffold(
      appBar: AppBar(
        title: Text('Test Index'),
      ),
      body: ListView.separated(
        itemCount: 5,
        padding: const EdgeInsets.only(top: 8.0, bottom: 8.0),
        separatorBuilder: (context, index) => const Divider(),
        itemBuilder: (context, index) {
          final _id = index + 1;
          final _tag = "hero_$index";
          final _img = 'https://i.ibb.co/193y0zv/programmer.webp';

          return ListTile(
            contentPadding: EdgeInsets.all(16.0),
            onTap: () {
              _navigator.push(
                MaterialPageRoute(
                  builder: (_) => TestView(id: _id, tag: _tag, img: _img),
                ),
              );
            },
            leading: Hero(tag: _tag, child: Image.network(_img)),
            title: Text("Hero ${_id}"),
          );
        },
      ),
    );
  }
}
```

### Page 2
```dart
class TestView extends StatelessWidget {
  final id;
  final tag;
  final img;
  const TestView({Key? key, this.id, this.tag, this.img}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final _db = context.read<AppDatabase>();

    return Scaffold(
      appBar: AppBar(
        title: Text('Test View'),
      ),
      body: FutureBuilder<Category>(
        // initialData: ??
        future: _db.categoriesDao.getCategory(id),
        builder: (context, snapshot) {
          if (snapshot.hasData) {
            // Hero widget does not work when navigated to this route
            // Standard sliding-up animation is only seen
            // Only triggers hero animation when user navigates back

            // use Category attributes here
            return Hero(
              tag: tag,
              child: Image.network(img),
            );
          }

          return const Center(child: CircularProgressIndicator());
        },
      ),
    );
  }
}
```

**Comment by simolus3** [comment]
Interesting question! Unfortunately there's not much that drift could magically do here to resolve the situation. Fundamentally, there's no way to synchronously run an async query, and there's no silver bullet for `initialData` that drift could provide for you. Just think about what `initialData` should contain: It obviously needs to be a full category because the types need to match, but then we need to get values for all of the columns out of thin air.

Which initial data to use while the query is running in the background depends on your UI and what to show. I think the easiest way to resolve this is to adapt the layout in the pushed page. For instance, could it be adapted so that the `Hero` is always shown? There could essentially be two states here:

1. Data is available in the `FutureBuilder` / `StreamBuilder`: Just show your regular layout, including the hero.
2. No data is available: Instead of showing nothing but a loading indicator, use a layout that already includes the hero at roughly the position it's going to be in in the end. For other components on that page, you could use something like the [shimmer](https://pub.dev/packages/shimmer) to indicate a loading state that doesn't break the whole layout.

This ensures that the hero is already there when the page is first built, so the  animation should work. This is a lot more work for you because it complicates the loading state UI, but if you want to combine a `Hero` with data that's loading I think this is theb est way to go.
An alternative would be to await the future in the `onTap` handler in the main screen and just pass the result to the `TestView`, which then wouldn't have to use a `FutureBuilder` at all. This only works when the future completes quickly, but for simple queries it should be fine.

So I don't think there's a way for drift to make this situation easier, but I'm happy to help with questions around handling loading state :)
