### ISSUE TITLE
Foreign key cascade delete bug

### ISSUE THREAD

**Issue by BojanDolic** [simolus3/drift#1788]
**Describe the bug**

I'm not exactly sure it is a bug but foreign keys didn't work for me while using `.references()`

I'm having two tables:
table `A` and table `B`

Table `A` has a primary key `id` and table `B` has it's primary key and column called `primary_id` which is going to be foreign key.
I'm using `references()` function to reference `primary_id` to the `id` of the table `B` like this:

```dart
IntColumn get primary_id => integer()
      .customConstraint("UNIQUE")
      .nullable()
      .references(A, #id,
          onDelete: KeyAction.cascade)();
```

I have enabled foreign keys inside migration like this:

```dart
@override
  MigrationStrategy get migration =>
      MigrationStrategy(beforeOpen: (details) async {
        await customStatement('PRAGMA foreign_keys = ON;');
      });
```

The problem is that when I delete a row from parent table `A`, the record inside table `B` doesn't get deleted.

I solved the problem using plain SQL:

```dart
IntColumn get primary_id => integer().nullable().customConstraint(
      "NULL UNIQUE REFERENCES A(id) ON DELETE CASCADE")();
```

This works fine and it deletes the child row if it exists.

**Comment by simolus3** [comment]
Oh, I can't believe I've missed this in the original discussion. The problem is that `customConstraint` overrides all column constraints that drift generates.

So doing

```dart
      .customConstraint("UNIQUE")
      .nullable()
      .references(A, #id,
          onDelete: KeyAction.cascade)();
```

is actually the same as just doing `.customConstraint("UNIQUE")()`, the reference clause will be overridden by the `customConstraint` call which sets _all_ constraints for the column that it is applied to.

This is mentioned in the documentation of `customConstraint`, but I agree that there should be better tooling to warn you here. I'll change the generator to emit warnings when `customConstraint` is used in combination with column builders.

**Comment by simolus3** [comment]
Generator warnings have been added in a721e896d3831336d64189cfd49cf73c31039fc4.
