### ISSUE TITLE
Name of column from view not properly escaped

### ISSUE THREAD

**Issue by knaeckeKami** [simolus3/drift#1814]
**Describe the bug**

When creating a View, is an issue with certain columns that are not named and have a static value.

**Repro**

Use this drift file:
```sql
CREATE VIEW IF NOT EXISTS repro AS
  SELECT 1;
```

and run build_runner.

Error:

```
[SEVERE] drift_dev:drift_dev on lib/src/db.dart:
An error `FormatterException` occurred while formatting the generated source for
  `package:drift_view_test/src/db.dart`
which was output to
  `lib/src/db.moor.g.part`.
This may indicate an issue in the generator, the input source code, or in the
source formatter.
Could not format because the source could not be parsed:

line 41, column 34 of .: A function body must be provided.
   ╷
41 │ late final GeneratedColumn<int?> 1 = GeneratedColumn<int?>('1', aliasedName, false, type: const IntType());
...
```

Note: in queries like 

```sql
create table a(b int);

testQuery:
SELECT 1,2, b
from a;
```

this works fine, and the name `empty`/`empty1` is chosen for the unnamed fields in the generated result class.

This is probably a low-prio bug, I just stumbled upon it when creating a minimal reproducible example of #1813 . It can easily be worked around by naming the result columns (e.g. writing `SELECT 1 as col`) ;

**Comment by simolus3** [comment]
Thanks for the report! I've fixed this in 847960202392c8f3e2ea28a1bb32628d73f3c62b.

-----

While I know this is just for an example, you'll really want to set aliases for view columns. From the [documentation](https://www.sqlite.org/c3ref/column_name.html):

> The name of a result column is the value of the "AS" clause for that column, if there is an AS clause. If there is no AS clause then the name of the column is unspecified and may change from one release of SQLite to the next. 

I don't think they'll ever actually change the default names because almost everyone relies on them, but that's a fair warning :D With the "soon" to be default `new_sql_code_generation` [build option](https://drift.simonbinder.eu/docs/advanced-features/builder_options/), drift will insert explicit names for select statements, but we don't do that for views. Starting to do so now would be breaking in the most annoying ways, so I think it's unlikely that this will change.
