### ISSUE TITLE
Support absurd-sql for web?

### ISSUE THREAD

**Issue by matehat** [simolus3/drift#1821]
Hello, and thanks a lot for the awesome library!

For more sustainable support on the web, do you think drift could work with [absurd-sql](https://github.com/jlongster/absurd-sql)?

It uses indexeddb as a storage backend for sql.js and is apparently much faster and safer than saving and loading all the data at once.

Thanks in advance for your opinion!

**Comment by simolus3** [comment]
Thanks for starting this discussion! I've also looked at some ways to stabilize the web implementation, especially with regards to performance.

In the next drift version, there will be a new `package:drift/wasm.dart` library providing a direct Dart wrapper around a patched sqlite3 version compiled to WebAssembly. With that implementation, we can start using IndexedDB as a virtual file system without having to export the whole database after each write. And since the whole implementation is written in Dart, we also avoid the external dependency to a JavaScript library. Internally, we can also share lots of code between the FFI and the WASM based implementations so you'll get a consistent library across platforms.

At the moment, this new implementation stores whole files in IndexedDB, but @westito started some interesting work to store contents in blocks which should speed up performance more. This is very close to what absurd sql is also doing internally. One missing part is a web worker implementation to synchronize IndexedDB operations.

So while this is still in development and pretty experimental at the moment, I think the new direct Dart wrapper around sqlite3 will end up being a more reliable approach than wiring up absurd-sql.
