### ISSUE TITLE
Custom functions

### ISSUE THREAD

**Issue by gisborne** [simolus3/drift#1828]
Applications that embed sqlite can [define custom functions](https://www.sqlite.org/appfunc.html#:~:text=Applications%20that%20use%20SQLite%20can,or%20can%20be%20loadable%20extensions.).

sqlite3 supports custom functions through [_createFunction_](https://pub.dev/documentation/sqlite3/latest/sqlite3.common/CommonDatabase/createFunction.html) and [_createAggregateFunction_](https://pub.dev/documentation/sqlite3/latest/sqlite3.common/CommonDatabase/createAggregateFunction.html).

This would be very much a non-trivial very useful feature yet probably not horrible to implement (particularly as it can be cribbed from sqlite3).

**Comment by simolus3** [comment]
The thing is that drift supports other implementations too (outside of `package:sqlite3`). For instance, we have an implementation that uses `sqflite` internally and there's experimental support for postgres too. So we can't have generalized support for custom functions since the different implementations have varying support for them.

The `NativeDatabase` constructors have a `setup` parameter which you can use to prepare the database before drift starts using it. This is a good place to register custom functions:

```dart
NativeDatabase(
  File('/foo/bar'),
  setup: (rawDb) {
    rawDb.createAggregateFunction(
      functionName: 'sumint',
      function: _SumInt(),
      argumentCount: const AllowedArgumentCount(1),
   );
  }
)
```
