### ISSUE TITLE
fts in flutter app

### ISSUE THREAD

**Issue by RokeAlvo** [simolus3/drift#1860]
how connect fts to flutter app?

connection:
```
Db(LazyDatabase(() async {
        return NativeDatabase(tempDbFile);
      })
)
```

query:
```
      final searchExpression = CustomExpression<bool>(
        '''
          Z_PK in (select rowid from product_fts where product_fts match "$configSearchString*") 
          OR Z_PK in (select ZPRODUCT from ZBARCODE where ZCODE LIKE "$configSearchString%")
          ''',
      );
      query.where((p) => searchExpression);
```
in test is all ok, but when i use db in application i got error:
```
SqliteException(1): no such column: ma*, SQL logic error (code 1)
  Causing statement: SELECT * FROM ZPRODUCT WHERE           Z_PK in (select rowid from product_fts where product_fts match "ma*") 
          OR Z_PK in (select ZPRODUCT from ZBARCODE where ZCODE LIKE "ma%")
          ;
```

it looks like the sqlite in application has no fts extension 
query without match works fine

**Comment by simolus3** [comment]
> it looks like the sqlite in application has no fts extension

fts5 is enabled with `sqlite3_flutter_libs`, older fts versions aren't.

> it looks like the sqlite in application has no fts extension

Apart from the possible [SQL injection](https://en.wikipedia.org/wiki/SQL_injection) with the `$configSearchString` in your query, the problem is that you're using double-quoted string literals, a [misfeature](https://www.sqlite.org/quirks.html#dblquote) that is disabled for the sqlite3 you get with `sqlite3_flutter_libs`.

The easiest way to fix this is to use something like `match '${SqlTypeSystem.mapToSqlConstant(configSearchString)}'` which uses single quotes and escapes the string. Even better would be to use drift's query builder with a custom expression for the match. You could write something like

```dart
/// Generates a match expression for fts5 tables
class MatchExpression extends Expression<bool> {
  final TableInfo _table;
  final String _match;

  MatchExpression(this._table, this._match);

  @override
  Precedence get precedence => Precedence.comparison;

  @override
  int get hashCode => Object.hash(MatchExpression, _table, _match);

  @override
  bool operator ==(Object other) {
    return other is MatchExpression &&
        other._table == _table &&
        other._match == _match;
  }

  @override
  void writeInto(GenerationContext context) {
    context.buffer
      ..write(escapeIfNeeded(_table.aliasedName))
      ..write(' MATCH ');
    writeInner(context, Variable.withString(_match));
  }
}
```

Then you can rewrite the search expression to:

```dart
final ftsMatch = selectOnly(productFts)
  ..addColumns([productFts.rowId])
  ..where(MatchExpression(productFts, configSearchString));

final likeMatch = selectOnly(zbarcode)
  ..addColumns([zbarcode.zproduct])
  ..where(zbarcode.zcode.like(''));

query.where((p) => p.zPk.isInQuery(ftsMatch) | p.zPk.isInQuery(likeMatch));
```

A bit more noisy for this example, but then drift takes care of not being vulnerable to SQL injections and whatnot :D

By the way, if you want to write some queries in SQL, I recommend using [compiled queries](https://drift.simonbinder.eu/docs/using-sql/custom_queries/#statements-with-a-generated-api) for that, for those drift can check at compile time that everything is valid.

**Comment by RokeAlvo** [comment]
thank you very much for answe

some comments:

```
final ftsMatch = selectOnly(productFts)
  ..addColumns([productFts.rowId]) // not works: Invalid argument(s): Cannot use rowId on a table without a rowid!
  ..where(MatchExpression(productFts, configSearchString));
  ```

solution:

add primary key from ZPRODUCT table to fts table
```sql
-- drift file
create virtual table product_fts using fts5 (
                 content_rowid=Z_PK,
                 Z_PK UNINDEXED, -- add primary key from ZPRODUCT table
                 ZTITLE,
                 ZID_FROM_SUPPLIER,
                 ZSUPPLIER_NAME,
                 content=ZPRODUCT
             );

```
and 
```dart
      final ftsMatch = selectOnly(productFts)
        ..addColumns([productFts.zPk])
        ..where(MatchExpression(productFts, '$configSearchString*'));
```
