### ISSUE TITLE
"artificial exception to rollback the transaction" causing deadlock with SqfliteQueryExecutor after upgrading Drift

### ISSUE THREAD

**Issue by Mike278** [simolus3/drift#1881]
This error started popping up on Crashlytics after upgrading from Moor 3.3.1 to Drift 1.6.0. 

It looks like it's caused by creating a stream inside a transaction, and then throwing an exception to rollback the transaction. Here's the repro I ended up with:

```dart
import 'dart:io';

import 'package:drift/drift.dart' hide Column;
import 'package:drift/native.dart';
import 'package:drift_sqflite/drift_sqflite.dart';
import 'package:flutter/widgets.dart' show WidgetsFlutterBinding;
import 'package:path_provider/path_provider.dart' show getApplicationDocumentsDirectory;


class EmptyDb extends GeneratedDatabase {
  EmptyDb(QueryExecutor q) : super(SqlTypeSystem.defaultInstance, q);
  @override final List<TableInfo> allTables = const [];
  @override final schemaVersion = 1;
}

EmptyDb sqflite() => EmptyDb(
  SqfliteQueryExecutor.inDatabaseFolder(path: 'sqflite_db.sqlite3')
);
EmptyDb ffi(Directory documents) => EmptyDb(
  NativeDatabase(File('${documents.path}/ffi_db.sqlite3'))
);

Future<void> _trx(EmptyDb db) {
  return db.transaction(() async {
    await db.customSelect('select 1').watchSingle().first;
    throw 'oops';
  });
}

Future<void> _query(EmptyDb db) async {
  await db.customSelect('select 1').getSingle().then((r) => print('select 1: $r'));
  await db.customSelect('select 2').watchSingle().first.then((r) => print('select 2: $r'));
}

Future<void> runTest(EmptyDb db) async {
  try {
    await db.customSelect('select 1').getSingle(); // ensure database is open/created
    await _trx(db);
  } catch (e) {
    print('caught $e');
  } finally {
    await _query(db).timeout(Duration(milliseconds: 500),
      onTimeout: () => throw 'deadlocked'
    );
  }
}


void main() async {
  driftRuntimeOptions.dontWarnAboutMultipleDatabases = true;
  WidgetsFlutterBinding.ensureInitialized();

  final ffiDb = ffi(await getApplicationDocumentsDirectory());
  final sqfliteDb = sqflite();

  await runTest(ffiDb);
  await runTest(sqfliteDb); // this throws 'deadlocked'
}
```

**Comment by Mike278** [comment]
It seems like this might be related to zones? The above repro no longer throws 'deadlocked' when I change [`runZonedGuarded`](https://github.com/simolus3/drift/blob/6a6d1268c48170824903c6879cee27fc27461654/drift/lib/src/runtime/cancellation_zone.dart#L15) to `runZoned` (with no `onError` callback).

**Comment by simolus3** [comment]
Thanks for the helpful issue! I can reproduce this locally, and I agree with the sentiment that this is probably due to some zones being misused. Now the question is whether the bug originates in drift, sqflite or Flutter.

The first worrying thing is that the "Exception: artificial exception to rollback the transaction" even shows up in the console, it should be caught by drift internally:

https://github.com/simolus3/drift/blob/6a6d1268c48170824903c6879cee27fc27461654/drift_sqflite/lib/drift_sqflite.dart#L94-L105

Even when I change that to

```dart
  @override
  void startTransaction(Future<void> Function(QueryDelegate) run) {
    delegate.db.transaction((transaction) async {
      final executor = _SqfliteTransactionExecutor(transaction);
      try {
        await run(executor).whenComplete(() => print('transaction complete'));
      } finally {
        print('done here?');
      }
    }).catchError((_) {
      // Ignore the error! We send a fake exception to indicate a rollback.
      // sqflite will rollback, but the exception will bubble up. Here we stop
      // the exception.
      print('caught internally');
    });
  }
```

Then neither `transaction complete`, `done here` or `caught internally` shows up in the logs :worried:

**Comment by simolus3** [comment]
Ok, I think I've found the problem. The flow is essentially

1. Your `transaction` block callback is called.
2. You run the select stream. This starts a new cancellation zone and calls `beforeOpen` on the transaction executor
3. Still in that cancellation zone, `beforeOpen` now calls `startTransaction` which calls sqflite's `transaction()` block and awaits the completer.
4. In an outer zone (not in the select), we now want to rollback the transaction.
5. Dart sees that the exception from the rollback is happening in an error zone that is different from the error zone awaiting the completer internally. As errors don't cross those boundaries, all catch/finally mechanisms are ignored and the async error is considered to be an unhandled exception.
6. The artificial exception gets printed and the callback to actually rollback the transaction never runs, since it lived in an ignored `finally` block in sqflite.

My somewhat hacky fix is to run the relevant parts of step 3 outside of the error zone. I think this is conceptually ok (after all, the transactions' lifecycle is bound to the zone where it was created, not where it is first used).

Ideally, I'd like to completely remove these jumps through completers and callbacks and just issue the `COMMIT`/`ROLLBACK` calls from drift instead of using sqflite's transaction APIs. Might be considered breaking though (if some users want to use the same sqflite database instance both with and without drift and are relying on sqflite's transaction lock). Certainly a good place to do some clean-up later :D

**Comment by Mike278** [comment]
Wow that's pretty subtle, nice find. I tried out [this branch](https://github.com/Mike278/drift/tree/latest-release%2Btransaction-hotfix) and it seems to fix the issue, just running it through CI now. Thanks so much for the quick fix!

Aside: it'd be nice if it was possible to use the `zoneValues` feature without also invoking the other (IMO harder-to-use) Zone features like exception handling :(
