### ISSUE TITLE
UNIXEPOCH in View becomes String instead of DateTime

### ISSUE THREAD

**Issue by the4thfloor** [simolus3/drift#1891]
```sql
CREATE TABLE IF NOT EXISTS foos
(
   foo DATETIME
) WITHOUT ROWID;


CREATE VIEW IF NOT EXISTS foo_bar AS
SELECT UNIXEPOCH('2022-06-17' || ' ' || '17:25', 'utc')                AS foo,
       IFNULL(f.foo, UNIXEPOCH('2022-06-17' || ' ' || '17:25', 'utc')) AS bar
FROM foos f;
```

The generated `DataClass` for the table `foos` looks good:
```dart
class Foo extends DataClass implements Insertable<Foo> {
  final DateTime? foo;
  Foo({this.foo});
  
  // ...
  
```

But the `DataClass` for the View `foo_bar` has `String`'s instead of `DateTime`'s:
```dart
class FooBarData extends DataClass {
  final String foo;
  final String bar;
  FooBarData({required this.foo, required this.bar});
  
  // ...

```

**Comment by simolus3** [comment]
This doesn't seem to be specific to views, we just generally ignore `UNIXEPOCH` function calls (we don't even interpret them as ints :scream: ).

I've changed this to a datetime value in c9bd7236c6a6a9c7d45b2781eab735a13f4030a8. It has to be nullable because `UNIXEPOCH` returns null for invalid time values or modifiers.
