### ISSUE TITLE
Selection no longer valid in `1.7.0` which where valid in `1.6.0`

### ISSUE THREAD

**Issue by RoarGronmo** [simolus3/drift#1903]
When calling this selection: 

```
    'getSelectedOffice':'SELECT * , (ofot.r_no = ust.text_value) as chosen '
        'FROM order_firms_offices_table as ofot '
        'LEFT JOIN user_selections_table as ust ON (ust.selection = \'office_no\') '
        'LEFT JOIN user_selections_table as ust2 ON (ust2.selection = \'firm_no\') '
        'WHERE ((chosen = TRUE ) AND (ust2.int_value = ofot.frm_no)) '
        'LIMIT 1 '
```

It runs perfectly in `1.6.0`, but fails in `1.7.0` with following error/warning:

```
[WARNING] drift_dev:drift_dev on lib/services/drift/database/m_work_database.dart:
The sql query getSelectedOffice is invalid: line 1, column 242: Unknown column.
  ╷
1 │ SELECT * , (ofot.r_no = ust.text_value) as chosen FROM order_firms_offices_table as ofot LEFT JOIN user_selections_table as ust ON (ust.selection = 'office_no') LEFT JOIN user_selections_table as ust2 ON (ust2.selection = 'firm_
no') WHERE ((chosen = TRUE ) AND (ust2.int_value = ofot.frm_no)) LIMIT 1
  │ 
             ^^^^^^
  ╵

```
Will this say that "resulting" columns isn't valid as `WHERE` values in 1.7.0, as `chosen` is here ? 

Isn't that a breaking change ?

**Comment by simolus3** [comment]
Thanks for the report!

> Isn't that a breaking change ?

I can understand the reasoning, but I'd consider this a bugfix. My understanding is that references to result columns aren't valid expressions outside of `ORDER BY` terms. Quoting the [sqlite3 docs](https://www.sqlite.org/lang_select.html#the_order_by_clause):

> If the ORDER BY expression is an identifier that corresponds to the alias of one of the output columns, then the expression is considered an alias for that column. 

I couldn't find anything in the docs indicating that this should be allowed outside of `ORDER BY` clauses, which is why the column resolver was revised in the latest version. sqlite3 is generally lenient around these cases, but I think there were problematic queries where this didn't work so I think it's an improvement to closely follow the documentation here.

In your query, you can just replace  `WHERE ((chosen = TRUE ) AND` with `WHERE (ofot.r_no = ust.text_value) AND`. Also note that this is a warning and not a strict compile error, drift should continue to generate useful code for the query. If _that_ broke, please let me know and I'll fix it.

So unless there is a problem in addition to the warning, I'll close this as "the linter got better" which I don't consider to be breaking.
