### ISSUE TITLE
DataClasses should be generated using freezed

### ISSUE THREAD

**Issue by topperspal** [simolus3/drift#1919]
Many of us generally use row classes because we want to create data classes with `freezed` ( with JsonSerialization ) to get nice copyWith and serialization features. So we want you to generate row data classes with the help of `freezed` and `json_serializable`.

Developing apps is very difficult time due to uncertain database schema. We need to change schema several time during during development so it is really difficult to maintain or I say sync to files, first is Table file and second is Row Data class file.

**Comment by simolus3** [comment]
You can use [custom row classes](https://drift.simonbinder.eu/docs/advanced-features/custom_row_classes/) to make drift use a class you wrote as a data class instead of generating its own one.

Using this mechanism should make it easy to use builders like `freezed` or `built_value` to generate the classes the way you want them to be, skipping drift's default way of generating them.

**Comment by topperspal** [comment]
This may be optional atleast. It is 🚀🔥
